import requests
import os
from typing import List, Dict, Any, Optional
from dotenv import load_dotenv

load_dotenv()

class JulesClient:
    """
    Client for interacting with the Google Jules API.
    """
    BASE_URL = "https://jules.googleapis.com/v1alpha"

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv('JULES_API_KEY')
        if not self.api_key:
            raise ValueError("JULES_API_KEY environment variable is not set and no api_key provided.")
        
        self.headers = {
            "X-Goog-Api-Key": self.api_key,
            "Content-Type": "application/json",
            "Accept": "application/json"
        }

    def _request(self, method: str, endpoint: str, params: Optional[Dict] = None, data: Optional[Dict] = None) -> Dict[str, Any]:
        url = f"{self.BASE_URL}/{endpoint.lstrip('/')}"
        response = requests.request(method, url, headers=self.headers, params=params, json=data)
        response.raise_for_status()
        return response.json()

    def list_sources(self) -> Dict[str, Any]:
        """Retrieve the list of available sources (e.g., GitHub repositories)."""
        return self._request("GET", "sources")

    def create_session(
        self, 
        prompt: str, 
        source_name: str, 
        branch: str,
        title: Optional[str] = None, 
         
        automation_mode: str = "AUTO_CREATE_PR", 
        require_plan_approval: bool = False
    ) -> Dict[str, Any]:
        """
        Creates a new session for Jules to work on.
        
        Args:
            prompt: The instruction for Jules.
            source_name: The name of the source (e.g., 'sources/github/owner/repo').
            title: Optional title for the session.
            branch: The starting branch of the repository.
            automation_mode: Mode of automation (e.g., 'AUTO_CREATE_PR').
            require_plan_approval: Whether the session requires explicit plan approval.
        """
        data = {
            "prompt": prompt,
            "sourceContext": {
                "source": source_name,
                "githubRepoContext": {
                    "startingBranch": branch
                }
            },
            "automationMode": automation_mode,
            "title": title or prompt,
            "requirePlanApproval": require_plan_approval
        }
        return self._request("POST", "sessions", data=data)

    def list_sessions(self, page_size: int = 10) -> Dict[str, Any]:
        """Lists recently created sessions."""
        params = {"pageSize": page_size}
        return self._request("GET", "sessions", params=params)

    def get_session(self, session_id: str) -> Dict[str, Any]:
        """Retrieve details of a specific session by its ID."""
        # Assuming endpoint is /sessions/{id} based on common Google API patterns
        return self._request("GET", f"sessions/{session_id}")

    def approve_plan(self, session_id: str) -> Dict[str, Any]:
        """Approve the plan generated by Jules for a session."""
        # Based on the prompt snippet "Step 4: Approve plan"
        return self._request("POST", f"sessions/{session_id}:approvePlan")

    def list_activities(self, session_id: str, page_size: int = 20) -> Dict[str, Any]:
        """List activities within a specific session."""
        params = {"pageSize": page_size}
        return self._request("GET", f"sessions/{session_id}/activities", params=params)

    def send_message(self, session_id: str, message: str) -> Dict[str, Any]:
        """Send a follow-up message to an existing session."""
        data = {"message": message}
        return self._request("POST", f"sessions/{session_id}:sendMessage", data=data)

# --- Wrapper functions for easy tool usage by LLM agents ---

def list_jules_sources() -> str:
    """Retrieve the list of available GitHub sources connected to Jules."""
    client = JulesClient()
    return str(client.list_sources())

def create_jules_session(prompt: str, source_name: str, title: Optional[str] = None) -> str:
    """
    Create a new Jules session to perform a task in a repository.
    Example source_name: 'sources/github/bobalover/boba'
    """
    client = JulesClient()
    return str(client.create_session(prompt=prompt, source_name=source_name, title=title))

def get_jules_session_status(session_id: str) -> str:
    """Check the current status and outputs of a Jules session."""
    client = JulesClient()
    # strip 'sessions/' prefix if present
    sid = session_id.replace("sessions/", "")
    return str(client.get_session(sid))

def approve_jules_plan(session_id: str) -> str:
    """Approve the plan for a Jules session to start execution."""
    client = JulesClient()
    sid = session_id.replace("sessions/", "")
    return str(client.approve_plan(sid))

def send_jules_message(session_id: str, message: str) -> str:
    """Send a message to an active Jules session to provide feedback or new instructions."""
    client = JulesClient()
    sid = session_id.replace("sessions/", "")
    return str(client.send_message(sid, message))

if __name__=="__main__":
    import postgres_agent
    from langchain_openrouter import ChatOpenRouter
    
    # Define tools available to the agent
    jules_tools = [
        list_jules_sources, 
        create_jules_session, 
        get_jules_session_status, 
        approve_jules_plan, 
        send_jules_message
    ]
    
    agent = postgres_agent.PersistentAgent(
        tools=jules_tools,
        llm=ChatOpenRouter(
            model="google/gemma-4-31b-it:free",
            api_key=os.getenv('OPEN_ROUTER_API')
        ),
        system_message="You are an expert developer agent capable of using the Jules API to automate software development tasks in GitHub repositories. You can list sources, create sessions, check status, and interact with the agent."
    )
    
    print(agent.chat(input("prompt: "), "user2"))
